parameters:
#    ititi_parsing.example.class: Ititi\ParsingBundle\Example

services:
#    ititi_parsing.example:
#        class: %ititi_parsing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
